### ISSUE TITLE
Project developing process

### ISSUE THREAD

**Issue by ParsaAminpour** [aforouz/Enigma_Simulator#1]
# Tasks for project management

[Mohammad Siamaki](https://github.com/mohammads2005)
- [x] #2
- [x] Writing the proper comment for each functions related to config and enigma file
- [x] Efficient the machine algorithm
- [x] write a cleaner code (mandatory)
- [x] work on output of the rotors

[Parsa Aminpour](https://github.com/ParsaAminpour)
- [x] Writing log record structure
- [x] writing a interpreter for the logs based on the initial config setup
- [x] establish a cloud database to store the keys for the verification part
- [x] Coding verification system with the Enigma machine verification algorithm
- [x] Coding the CLI output framework
- [x] Writing test units for the CLI frame (based on enigma I/O)

[Alireza Ahmadi](https://github.com/Wolfe1729)
- [x] Setup the config file
- [x] Managing input/output process

[Mohammad Ebrahimian](https://github.com/m0ebraahim)
- [x] writing test unit for the Enigma algorithm
- [x] N/A

[Mohammad Kazemaini](https://github.com/M-H-K-ir)
- [x] N/A

**Comment by Wolfe1729** [comment]
Options Done
